// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
// / await Firebase.initializeApp(
// /   options: DefaultFirebaseOptions.currentPlatform,
// / );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAN-nrb_GocxdJzIqpUIs-BarfQdqaS8Rk',
    appId: '1:184007945915:web:d640a06b063aac913d039e',
    messagingSenderId: '184007945915',
    projectId: 'platzy-trips-flutter',
    authDomain: 'platzy-trips-flutter.firebaseapp.com',
    storageBucket: 'platzy-trips-flutter.appspot.com',
    measurementId: 'G-FZ38YVX30M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFoAmVVBCerfw0S5Gsxg4Y29r_5AeNzww',
    appId: '1:184007945915:android:8fd1e5bab5b920363d039e',
    messagingSenderId: '184007945915',
    projectId: 'platzy-trips-flutter',
    storageBucket: 'platzy-trips-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-ETAB_eoW_GTFYnTlP22-uZTjNfhxJYQ',
    appId: '1:184007945915:ios:6ee7b3065291739e3d039e',
    messagingSenderId: '184007945915',
    projectId: 'platzy-trips-flutter',
    storageBucket: 'platzy-trips-flutter.appspot.com',
    iosClientId:
        '184007945915-j1q0meb4e9t3fm542mit1cqb0hrlej1o.apps.googleusercontent.com',
    iosBundleId: 'com.example.curzoAvanzadoFlutterPlat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-ETAB_eoW_GTFYnTlP22-uZTjNfhxJYQ',
    appId: '1:184007945915:ios:cf843be09c1c746b3d039e',
    messagingSenderId: '184007945915',
    projectId: 'platzy-trips-flutter',
    storageBucket: 'platzy-trips-flutter.appspot.com',
    iosClientId:
        '184007945915-torj9n4o5kfp60mjg6ujdc3krt7majp4.apps.googleusercontent.com',
    iosBundleId: 'com.platzytrips.app',
  );
}
